import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";

// Define the custom Geist Sans font for the project
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Define the custom Geist Mono font for the project
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the project, such as description
export const metadata: Metadata = {
  description: "Generated by create next app", // The description shown for the site
};

// RootLayout component to wrap the entire application layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // Children prop is passed in to display main content
}>) {
  return (
    <html lang="en"> {/* Set the language of the page to English */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`} // Apply the custom fonts and other utility classes
      >
        {/* Navbar component displayed at the top of the page */}
        <Navbar />

        {/* Main content area */}
        <main className="flex-grow container mx-auto p-4">
          {children} {/* Render the children (main content) here */}
        </main>

        {/* Footer component displayed at the bottom of the page */}
        <Footer />
      </body>
    </html>
  );
}
